---
- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/6.x/apt stable main'
    state: present
    update_cache: yes

- name: Install Elasticsearch.
  apt:
    pkg: elasticsearch
    state: present

- name: Configure Elasticsearch.
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "network.host:"
      line: "network.host: {{ elasticsearch_network_host }}"
    - regexp: "http.port:"
      line: "http.port: {{ elasticsearch_http_port }}"
    - regexp: "cluster.name:"
      line: "cluster.name: {{ elasticsearch_cluster_name }}"
    - regexp: "node.name:"
      line: "node.name: {{ elasticsearch_node_name }}"
  notify: restart elasticsearch

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for: host={{ elasticsearch_network_host }} port={{ elasticsearch_http_port }} delay=3 timeout=300